// Admin GET all accounts api
GET http://localhost:5000/api/admin/get-all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDlmOGVmNzU1MjM5ZTMyNjQ2YTgzNDYiLCJhZG1pbklkIjoiMjAyMS0wMDAyIiwidHlwZSI6ImFkbWluIiwicm9sZSI6IiIsInBlcm1pc3Npb25zIjpbXSwiaWF0IjoxNjIxMDY5NjAxLCJleHAiOjE2MjE2NzQ0MDF9.-p281PVFs2WaFdNMyp9mM5O1eYXxmUYpcr146YxZ8u4

###

// Admin DELETE Account
DELETE http://localhost:5000/api/admin/delete/:adminId
Content-Type: application/json
Authorization:


###

// please replace the :id with your database _id value eg. 60a0a43f615c1c0cf0d15429
GET http://localhost:5000/api/admin/:id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDlmOGVmNzU1MjM5ZTMyNjQ2YTgzNDYiLCJhZG1pbklkIjoiMjAyMS0wMDAyIiwidHlwZSI6ImFkbWluIiwicm9sZSI6IiIsInBlcm1pc3Npb25zIjpbXSwiaWF0IjoxNjIxMDY5NjAxLCJleHAiOjE2MjE2NzQ0MDF9.-p281PVFs2WaFdNMyp9mM5O1eYXxmUYpcr146YxZ8u4


###

// note: Please replace the ID after the /update to your own _id from your database
PUT http://localhost:5000/api/admin/update/60a0a43f615c1c0cf0d15428
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDlmOGVmNzU1MjM5ZTMyNjQ2YTgzNDYiLCJhZG1pbklkIjoiMjAyMS0wMDAyIiwidHlwZSI6ImFkbWluIiwicm9sZSI6IiIsInBlcm1pc3Npb25zIjpbXSwiaWF0IjoxNjIxMDY5NjAxLCJleHAiOjE2MjE2NzQ0MDF9.-p281PVFs2WaFdNMyp9mM5O1eYXxmUYpcr146YxZ8u4

{
    "adminId": "2021-0002",
    "contactNumber": {
        "mobileNumber": ["095031414124"],
        "landLineNumber": []
    },
    "homeAddress": {
        "homeNumOrLotNum": "",
        "streetName": "",
        "districtOrTown": "",
        "zipCode": "",
        "province": "",
        "country": ""
    },
    "permanentAddress": {
        "homeNumOrLotNum": "",
        "streetName": "",
        "districtOrTown": "",
        "zipCode": "",
        "province": "",
        "country": ""
    },
    "currentAddress": {
        "homeNumOrLotNum": "",
        "streetName": "",
        "districtOrTown": "",
        "zipCode": "",
        "province": "",
        "country": ""
    },
    "nationality": ""
}

###

PUT http://localhost:5000/api/admin/update/permission-role/60a0a43f615c1c0cf0d15429
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDlmOGVmNzU1MjM5ZTMyNjQ2YTgzNDYiLCJhZG1pbklkIjoiMjAyMS0wMDAyIiwidHlwZSI6ImFkbWluIiwicm9sZSI6IiIsInBlcm1pc3Npb25zIjpbXSwiaWF0IjoxNjIxMDY5NjAxLCJleHAiOjE2MjE2NzQ0MDF9.-p281PVFs2WaFdNMyp9mM5O1eYXxmUYpcr146YxZ8u4

{
    "permissions": ["60a0a43f615c1c0cf0d1543c", "60a0a43f615c1c0cf0d1543d"],
    "role": "Test"
}

