// GET All Employee Information api
GET http://localhost:5000/api/employeeInformations/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDlmOGVmNzU1MjM5ZTMyNjQ2YTgzNDYiLCJhZG1pbklkIjoiMjAyMS0wMDAyIiwidHlwZSI6ImFkbWluIiwicm9sZSI6IiIsInBlcm1pc3Npb25zIjpbXSwiaWF0IjoxNjIxMDY5NjAxLCJleHAiOjE2MjE2NzQ0MDF9.-p281PVFs2WaFdNMyp9mM5O1eYXxmUYpcr146YxZ8u4

###

// GET One Employee Information api
GET http://localhost:5000/api/employeeInformations/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDlmOGVmNzU1MjM5ZTMyNjQ2YTgzNDYiLCJhZG1pbklkIjoiMjAyMS0wMDAyIiwidHlwZSI6ImFkbWluIiwicm9sZSI6IiIsInBlcm1pc3Npb25zIjpbXSwiaWF0IjoxNjIxMDY5NjAxLCJleHAiOjE2MjE2NzQ0MDF9.-p281PVFs2WaFdNMyp9mM5O1eYXxmUYpcr146YxZ8u4

###

// POST add Employee Information api
POST http://localhost:5000/api/employeeInformations/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDlmOGVmNzU1MjM5ZTMyNjQ2YTgzNDYiLCJhZG1pbklkIjoiMjAyMS0wMDAyIiwidHlwZSI6ImFkbWluIiwicm9sZSI6IiIsInBlcm1pc3Npb25zIjpbXSwiaWF0IjoxNjIxMDY5NjAxLCJleHAiOjE2MjE2NzQ0MDF9.-p281PVFs2WaFdNMyp9mM5O1eYXxmUYpcr146YxZ8u4

{
    "employee": "60a45d694c45e4243847bc1F",
    "employment": {
        "classification": "1234",
        "tenureShip": "1234"
    },
    "employmentHistory": {
        "employmentStart": "",
        "employmentEnd": "",
        "contractStart": "",
        "contractEnd": "",
        "probationStart": "",
        "probationEnd": "",
        "regularizationStart": "",
        "regularizationEnd": ""
    },
    "department": {
        "departmentId": "",
        "unit": "",
        "departmentName": "",
        "office": ""
    },
    "governmentIssuedNumbers": {
        "sss": "",
        "gsis": "",
        "tin": "",
        "philhealth": "",
        "pagibig": "",
        "universalId": "",
        "dln": "",
        "prc": ""
    },
    "immediateSuperior": "60a45d694c45e4243847bc19",
    "civilStatus": "",
    "emailAddresses": {
        "email1": "",
        "email2": ""
    },
    "religion": ""
}
###

// PATCH update Employee Information api
PATCH http://localhost:5000/api/employeeInformations/:id
Content-Type: application/json
Authorization:Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDlmOGVmNzU1MjM5ZTMyNjQ2YTgzNDYiLCJhZG1pbklkIjoiMjAyMS0wMDAyIiwidHlwZSI6ImFkbWluIiwicm9sZSI6IiIsInBlcm1pc3Npb25zIjpbXSwiaWF0IjoxNjIxMDY5NjAxLCJleHAiOjE2MjE2NzQ0MDF9.-p281PVFs2WaFdNMyp9mM5O1eYXxmUYpcr146YxZ8u4

{
    "employee": "60a45d694c45e4243847bc18",
    "employment": {
        "classification": "1234",
        "tenureShip": "1234"
    },
    "employmentHistory": {
        "employmentStart": "",
        "employmentEnd": "",
        "contractStart": "",
        "contractEnd": "",
        "probationStart": "",
        "probationEnd": "",
        "regularizationStart": "",
        "regularizationEnd": ""
    },
    "department": {
        "departmentId": "",
        "unit": "",
        "departmentName": "",
        "office": ""
    },
    "governmentIssuedNumbers": {
        "sss": "",
        "gsis": "",
        "tin": "",
        "philhealth": "",
        "pagibig": "",
        "universalId": "",
        "dln": "",
        "prc": ""
    },
    "immediateSuperior": "60a45d694c45e4243847bc19",
    "civilStatus": "",
    "emailAddresses": {
        "email1": "",
        "email2": ""
    },
    "religion": ""
}
###

// DELETE delete Employee Information api
DELETE http://localhost:5000/api/employeeInformations/:id
Content-Type: application/json
Authorization:Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDlmOGVmNzU1MjM5ZTMyNjQ2YTgzNDYiLCJhZG1pbklkIjoiMjAyMS0wMDAyIiwidHlwZSI6ImFkbWluIiwicm9sZSI6IiIsInBlcm1pc3Npb25zIjpbXSwiaWF0IjoxNjIxMDY5NjAxLCJleHAiOjE2MjE2NzQ0MDF9.-p281PVFs2WaFdNMyp9mM5O1eYXxmUYpcr146YxZ8u4

###