###

// GET All Permissions
DELETE http://localhost:5000/api/admin/get-all-permissions
Content-Type: application/json
Authorization:


###

// GET One Permission
DELETE http://localhost:5000/api/admin/get-one-permission/:id
Content-Type: application/json
Authorization: